-- Pointer only. Canonical SQL lives in:
-- https://github.com/karthikganjam99kg/urban-iq-backend/blob/main/supabase/schema.sql
--
-- This frontend talks to:
--   GET  /api/traffic-history  -> traffic_realtime (Flask + secret key)
--   GET  /api/alerts           -> alerts (Flask + secret key)
--   table road_damage          -> browser publishable key (RLS insert/select)
